/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.Random;
import javax.swing.JFileChooser;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import Utilerias.JTable.ColorCeldas;
import java.awt.Color;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ayram
 */
public class Forma extends javax.swing.JFrame {

    /**
     * Creates new form Forma
     */
    Random ran = new Random();
    JFileChooser selArch;
    Producto[]lista = new Producto[11];
    DefaultTableModel modelo;
    //int vec[][];
    public Forma() {
        initComponents();
        
        Locale.setDefault(Locale.US);
        
        modelo = (DefaultTableModel)jTable1.getModel();
        modelo.setRowCount(lista.length);
        
        for(int r=0; r<lista.length; r++)
            lista[r] = new Producto();
        
        jCheckBox1.setSelected(true);
        jTextFecha.setText(FechaActual());
        jTextHora.setText(HoraActual());
        
               
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.RIGHT);
        jTable1.getColumnModel().getColumn(2).setCellRenderer(tcr);
        jTable1.getColumnModel().getColumn(3).setCellRenderer(tcr);
        jTable1.getColumnModel().getColumn(4).setCellRenderer(tcr);
        
        jTextField1.setText(10144+ran.nextInt(250)+"");
        Mostrar();
    }
    
    public void Mostrar()
    {
        double total = 0;
        int can = 0; 
        DecimalFormat f = new DecimalFormat("#,###.00");
        
        for(int r=0; r<jTable1.getRowCount(); r++)
        {
            
            jTable1.setValueAt(lista[r].getProducto(), r, 0);
            jTable1.setValueAt(lista[r].getCodigo(), r, 1);
            jTable1.setValueAt(f.format(lista[r].getPrecio()), r, 2);
            jTable1.setValueAt(lista[r].getCantidad(), r, 3);
            jTable1.setValueAt(f.format(lista[r].Total()), r, 4);
                       
            total += lista[r].Total();
            can += lista[r].getCantidad();
        }
        
        jTextTotal.setText(f.format(total));
        jTextCanPro.setText(can+"");
    }
    
    private void limpiar()
    {
        jTextProducto.setText("");
        jTextPrecio.setText("");
        jTextCantidad.setText("");
        jTextCodigo.setText("");
   }

    public static String FechaActual()
    {
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatoFecha.format(fecha);         
    }
    
    public static String HoraActual()
    {
        Date hora = new Date();
        SimpleDateFormat formatoDateFormat = new SimpleDateFormat("hh:mm:ss");
        return formatoDateFormat.format(hora);  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCBProducto = new javax.swing.JComboBox<>();
        jCBCodigo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFecha = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTextCodigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextCantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextProducto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextPrecio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButIngresar = new javax.swing.JButton();
        jButAleatorios = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextCanPro = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSpinPosicion = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jTextHora = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jFile = new javax.swing.JMenu();
        jMINuevo = new javax.swing.JMenuItem();
        jMIAbrir = new javax.swing.JMenuItem();
        jMIAgregar = new javax.swing.JMenuItem();
        jMIGuardar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Busqueda de:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 102, 204))); // NOI18N

        jCBProducto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCBProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Producto" }));
        jCBProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBProductoActionPerformed(evt);
            }
        });

        jCBCodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCBCodigo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo" }));
        jCBCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCBCodigo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jCBProducto, 0, 148, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jCBProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Fecha");

        jTextFecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 102, 204))); // NOI18N

        jTextCodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Codigo");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Cantidad");

        jTextCantidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Produto");

        jTextProducto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Precio");

        jTextPrecio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("Fruteria ");

        jButIngresar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButIngresar.setText("Ingresar");
        jButIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButIngresarActionPerformed(evt);
            }
        });

        jButAleatorios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Venta N°");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Total a pagar:");

        jTextTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("N° de Productos");

        jTextCanPro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jSpinPosicion.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel13.setText("Posicion");

        jCheckBox1.setText("Incrementar");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Hora");

        jTextHora.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Codigo", "Precio", "Cantidad", "Total"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jFile.setText("File");

        jMINuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMINuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/text-4.png"))); // NOI18N
        jMINuevo.setText("Nuevo");
        jMINuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMINuevoActionPerformed(evt);
            }
        });
        jFile.add(jMINuevo);

        jMIAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMIAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder-3.png"))); // NOI18N
        jMIAbrir.setText("Abrir");
        jMIAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAbrirActionPerformed(evt);
            }
        });
        jFile.add(jMIAbrir);

        jMIAgregar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMIAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/090-add.png"))); // NOI18N
        jMIAgregar.setText("Agregar");
        jFile.add(jMIAgregar);

        jMIGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMIGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/062-diskette.png"))); // NOI18N
        jMIGuardar.setText("Guardar");
        jMIGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGuardarActionPerformed(evt);
            }
        });
        jFile.add(jMIGuardar);

        jMenuBar1.add(jFile);

        jMenu4.setText("Edit");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(jTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel14)
                    .addComponent(jTextHora, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButIngresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButAleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextCanPro, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)
                        .addGap(295, 295, 295)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextTotal)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel12))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButIngresar)
                            .addComponent(jButAleatorios))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextCanPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jSpinPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel4)
                    .addComponent(jTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButIngresarActionPerformed
        // TODO add your handling code here:
        Producto pro = new Producto();
        ClassPila pila = new ClassPila(lista.length);
        //ClaseCola cola = new ClaseCola(lista.length);

        if(pila.estaVacia())
        {
            
            for(int r=0; r<=lista.length; r++)
            {
                pro.setProducto(jTextProducto.getText());
                pro.setPrecio(Integer.parseInt(jTextPrecio.getText()));
                pro.setCantidad(Integer.parseInt(jTextCantidad.getText()));
                pro.setCodigo(Integer.parseInt(jTextCodigo.getText()));
            }
            jCBProducto.addItem(jTextProducto.getText());
            jCBCodigo.addItem(jTextCodigo.getText());
        }
        
       // Mostrar();
        //if(pila.esta_Llena())
        //          jCheckBox1.setSelected(false);

        int posicion = (int)jSpinPosicion.getValue()-1;

        lista[posicion] = pro;

        Mostrar();
        limpiar();

        if (jCheckBox1.isSelected())
        if (posicion == lista.length-1)
            jButIngresar.setEnabled(false);
        //jSpinPosicion.setValue(1);
        else
        jSpinPosicion.setValue(posicion+2);

        //Activar();
    }//GEN-LAST:event_jButIngresarActionPerformed

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here:
        Random azar = new Random();

        String [] prod = {"Queso","Huevo","Pan","Frijol","Tortillas","Manzana",
            "Papa","Cebolla","Chile","Tomate","Lechuga","Pera","Platano",
            "Oregano","Azucar","Calabaza","Elote","Repollo","Durazno","Uva","Naranja",
            "Mandarina","Guayaba","Harina","Mantequilla","Coco","Apio","Repollo","Cilantro",
            "Zanahoria","Tomillo","Col","Brocoli","Coliflor","Berenjena","Crema","Lechera",
            "Galletas","Mango","Jicama","Fresa","Piña"};

        jTextProducto.setText(prod[azar.nextInt(prod.length)]);
        jTextPrecio.setText(10+azar.nextInt(50)+"");
        jTextCantidad.setText(1+azar.nextInt(9)+"");

        jTextCodigo.setText(99999+azar.nextInt(99999)+"");
        
        
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jCBProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBProductoActionPerformed
        // TODO add your handling code here:
        String dato = jCBProducto.getSelectedItem().toString();
        Numero pos = new Numero();
        ColorCeldas celdas = new ColorCeldas(jTable1);
        
        ClassBusqueda.Secuencial_Datos_Desordenados(lista, dato, pos);
        
        if(pos.num != -1)
            
        celdas.addCelda(pos.num, 0, Color.yellow);
        
        celdas.repaint();
    }//GEN-LAST:event_jCBProductoActionPerformed

    private void jMINuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMINuevoActionPerformed
        // TODO add your handling code here:
        jSpinPosicion.setValue(1);
        //limpiar();
        jTextTotal.setText("");
        jTextCanPro.setText("");
        
        for(int r=0; r<modelo.getRowCount(); r++)
        {
            for(int c=0; c<modelo.getColumnCount(); c++)
                jTable1.setValueAt("", r, c);
        }
        jTextFecha.setText(FechaActual());
        jTextHora.setText(HoraActual());
        jTextField1.setText(10144+ran.nextInt(250)+"");
    }//GEN-LAST:event_jMINuevoActionPerformed

    private void jMIAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAbrirActionPerformed
        // TODO add your handling code here:
        ClaseArchivoBinarioEntero archivo = new ClaseArchivoBinarioEntero();
        Numero datos = new Numero();
        
        selArch = new JFileChooser();
        int valor = selArch.showOpenDialog(this);
        if(valor == JFileChooser.APPROVE_OPTION)
        {
            String nomArchivo = selArch.getSelectedFile().toString();
            archivo.leerVecEnArchivo(nomArchivo, datos, modelo);
        }
        jSpinPosicion.setValue(datos.num);
        jTextCantidad.setText(datos.num+"");
        jTextCanPro.setText(datos.num+"");
    }//GEN-LAST:event_jMIAbrirActionPerformed

    private void jMIGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGuardarActionPerformed
        // TODO add your handling code here:
        if(selArch.showOpenDialog(jPanel1) !=0)
            return;
        
        FileWriter fw = null;
        PrintWriter pw = null;
        
        try {
            fw = new FileWriter(selArch.getSelectedFile());
            pw = new PrintWriter(fw);
            
            pw.println(modelo.getRowCount());
            
            for(int r=0; r<modelo.getRowCount(); r++)
                for(int c=0; c<modelo.getColumnCount(); c++)
                    pw.println(modelo.getValueAt(r, c));
            
            pw.println(jCBProducto.getItemListeners());
            pw.println(jCBProducto.getItemListeners());
                    
        } catch (IOException ex) {
            Logger.getLogger(Forma.class.getName()).log(Level.SEVERE, null, ex);
        }    
        
        finally {
            if(pw != null)
                pw.close();
            try
            {
            if(fw != null)
                fw.close();
            } catch (IOException ex) {
                Logger.getLogger(Forma.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
            /*selArch.showSaveDialog(jMIGuardar);
            int[][] vec = new int [modelo.getRowCount()][modelo.getColumnCount()];
            
            for(int r=0; r<vec.length; r++)
            {
            for(int c=0; c<vec.length-1; c++)
            vec[r][c] = Integer.parseInt(modelo.getValueAt(r, c).toString());
            }
            
            ClaseArchivoBinarioEntero archivo = new ClaseArchivoBinarioEntero();
            
            selArch = new JFileChooser();
            int valor = selArch.showSaveDialog(this);
            if(valor == JFileChooser.APPROVE_OPTION)
            {
            String nomArch = selArch.getSelectedFile().toString();
            archivo.guardarVecEnArchivo(nomArch, vec);
            }*/
            
            /* for (int r=0; r<modelo.getRowCount(); r++)
            {
            dos.writeUTF(modelo.getValueAt(r, 0)+"");
            
            for (int c=1; c<modelo.getColumnCount()-1; c++)
            dos.writeInt(Integer.parseInt(modelo.getValueAt(r, c)+""));
            }*/
        
        
    }//GEN-LAST:event_jMIGuardarActionPerformed

    private void jCBCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBCodigoActionPerformed
        // TODO add your handling code here:
        int dato = Integer.parseInt(jCBCodigo.getSelectedItem().toString());
        Numero pos = new Numero();
        ColorCeldas celdas = new ColorCeldas(jTable1);
        
        ClassBusqueda.SDD(lista, dato, pos);
        
        if(pos.num != -1)
            
        celdas.addCelda(pos.num, 1, Color.yellow);
        
        celdas.repaint();
    }//GEN-LAST:event_jCBCodigoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButIngresar;
    private javax.swing.JComboBox<String> jCBCodigo;
    private javax.swing.JComboBox<String> jCBProducto;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JMenu jFile;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMIAbrir;
    private javax.swing.JMenuItem jMIAgregar;
    private javax.swing.JMenuItem jMIGuardar;
    private javax.swing.JMenuItem jMINuevo;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinPosicion;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextCanPro;
    private javax.swing.JTextField jTextCantidad;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextFecha;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextHora;
    private javax.swing.JTextField jTextPrecio;
    private javax.swing.JTextField jTextProducto;
    private javax.swing.JTextField jTextTotal;
    // End of variables declaration//GEN-END:variables
}
